{% set name = "bugout" %}
{% set version = "0.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 76c0a948678accd07dbbd980ea5a45314930b0998d39e22a293ce9c6061a2015

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - bugout-py = bugout.__main__:main

requirements:
  host:
    - pip
    - pydantic >=1.6
    - python
    - requests
  run:
    - pydantic >=1.6
    - python
    - requests

test:
  imports:
    - bugout
  commands:
    - bugout-py --help

about:
  home: "https://github.com/bugout-dev/bugout-python"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Python client library for Bugout API"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
