{% set name = "dataclasses" %}
{% set version = "0.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 8479067f342acf957dc82ec415d355ab5edb7e7646b90dc6e2fd1d96ad084c97

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: "https://github.com/ericvsmith/dataclasses"
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: "A backport of the dataclasses module for Python 3.6"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
